# Generated by Django 6.0.6 on 2026-09-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
